JSON_CONTRACT = """
===============================================================================
SECTION 9 : RESPONSE JSON CONTRACT SPECIFICATION
===============================================================================

OVERVIEW
-------------------------------------------------------------------------------

Defines the mandatory response structure, schema validation rules, serialization
requirements, data integrity constraints, field specifications, compatibility
standards, error handling policies, and output verification procedures for every
response generated by the AI Code Analysis Engine.

The Response JSON Contract serves as the formal communication interface between
the AI analysis engine and all downstream consumers, including backend services,
frontend applications, dashboards, APIs, analytics systems, and future
integrations.

Every response generated by the AI MUST strictly conform to this specification.
Responses violating this contract are considered invalid regardless of the
quality of the underlying analysis.

The AI must produce a single, valid, deterministic JSON object without any
additional explanations, markdown formatting, comments, or natural language
outside the specified schema.

===============================================================================
9.1 PURPOSE
===============================================================================

Define the purpose, scope, and responsibilities of the Response JSON Contract.

===============================================================================
9.2 PRIMARY OBJECTIVES
===============================================================================

Primary objectives include:

• Ensure deterministic output
• Guarantee machine-readable responses
• Maintain frontend compatibility
• Preserve backend interoperability
• Support future extensibility
• Prevent malformed responses
• Enable reliable parsing
• Standardize all analysis results

===============================================================================
9.3 RESPONSE GENERATION PRINCIPLES
===============================================================================

Every response must be:

• Complete
• Deterministic
• Valid JSON
• Schema compliant
• Consistent
• Language independent
• Self-contained
• Machine readable
• Human understandable

===============================================================================
9.4 ROOT-LEVEL RESPONSE SCHEMA
===============================================================================

Define every required top-level field including:

• success
• language
• problem_title
• overall_score
• correctness
• readability
• optimization
• code_quality
• analysis

Specify purpose, constraints, expected values, and validation rules for each.

===============================================================================
9.5 ANALYSIS OBJECT SCHEMA
===============================================================================

Define the internal analysis object including:

• syntax_errors
• logical_errors
• corrected_code
• optimized_code
• time_complexity
• space_complexity
• optimization_suggestions
• educational_feedback
• confidence

===============================================================================
9.6 SYNTAX ERROR OBJECT SPECIFICATION
===============================================================================

Each syntax error object must define:

• Line Number
• Error Type
• Severity
• Description
• Suggested Fix

All fields must follow standardized formatting.

===============================================================================
9.7 LOGICAL ERROR OBJECT SPECIFICATION
===============================================================================

Each logical error object must include:

• Line Number
• Error Category
• Severity
• Explanation
• Suggested Resolution

===============================================================================
9.8 OPTIMIZATION SUGGESTION OBJECT SPECIFICATION
===============================================================================

Each optimization recommendation should include:

• Current Approach
• Recommended Approach
• Expected Improvement
• Complexity Impact
• Explanation

===============================================================================
9.9 EDUCATIONAL FEEDBACK OBJECT SPECIFICATION
===============================================================================

Educational feedback should include:

• Strengths
• Weaknesses
• Learning Recommendations
• Suggested Topics
• Suggested Practice Problems
• Key Takeaways

===============================================================================
9.10 COMPLEXITY REPORTING SPECIFICATION
===============================================================================

Complexity reporting must define:

• Current Time Complexity
• Optimized Time Complexity
• Current Space Complexity
• Optimized Space Complexity

Use standard Big-O notation.

===============================================================================
9.11 SCORE REPORTING SPECIFICATION
===============================================================================

All scores must:

• Be numeric
• Remain within valid ranges
• Follow scoring rules
• Remain internally consistent
• Match supporting analysis

===============================================================================
9.12 SUCCESS RESPONSE RULES
===============================================================================

A successful response must contain every mandatory field.

No required field may be omitted.

===============================================================================
9.13 FAILURE RESPONSE RULES
===============================================================================

When analysis cannot be completed, return a valid JSON response that clearly
communicates failure while preserving schema integrity.

===============================================================================
9.14 REQUIRED FIELDS
===============================================================================

Define fields that must always exist regardless of analysis outcome.

===============================================================================
9.15 OPTIONAL FIELDS
===============================================================================

Define fields that may be omitted only when explicitly permitted.

===============================================================================
9.16 FIELD VALIDATION RULES
===============================================================================

Each field must satisfy:

• Correct name
• Correct type
• Correct format
• Valid range
• Logical consistency

===============================================================================
9.17 DATA TYPE REQUIREMENTS
===============================================================================

Specify expected data types for every field.

Examples:

Boolean
Integer
Float
String
Array
Object

===============================================================================
9.18 NULL VALUE RULES
===============================================================================

Avoid null values whenever possible.

Use empty strings or empty collections only when permitted by the schema.

===============================================================================
9.19 EMPTY COLLECTION RULES
===============================================================================

When no issues exist:

syntax_errors → []

logical_errors → []

optimization_suggestions → []

educational_feedback → []

Never omit these fields.

===============================================================================
9.20 DEFAULT VALUE RULES
===============================================================================

Define standardized default values for every optional field.

===============================================================================
9.21 SERIALIZATION RULES
===============================================================================

Responses must:

• Produce valid UTF-8 JSON
• Contain no comments
• Contain no markdown
• Contain no trailing commas
• Preserve field ordering where required

===============================================================================
9.22 SCHEMA VALIDATION RULES
===============================================================================

Validate every generated response against the official response schema before
returning it.

===============================================================================
9.23 BACKWARD & FORWARD COMPATIBILITY
===============================================================================

Future schema changes must preserve compatibility whenever possible.

Breaking changes should only occur through explicit schema version updates.

===============================================================================
9.24 ERROR RESPONSE SPECIFICATION
===============================================================================

Error responses should communicate:

• Failure status
• Failure reason
• Recoverability
• Safe defaults

while maintaining JSON validity.

===============================================================================
9.25 MULTI-LANGUAGE CONSIDERATIONS
===============================================================================

The schema must remain identical regardless of programming language.

Only analysis content may vary.

===============================================================================
9.26 VERSIONING STRATEGY
===============================================================================

Define rules governing future schema evolution, compatibility, and migration.

===============================================================================
9.27 DATA INTEGRITY REQUIREMENTS
===============================================================================

Ensure every reported metric, recommendation, explanation, and score is
internally consistent and supported by the analysis.

No contradictory information should exist anywhere within the response.

===============================================================================
9.28 OUTPUT CONSISTENCY RULES
===============================================================================

Repeated analysis of identical code under identical conditions should generate
structurally identical responses.

===============================================================================
9.29 QUALITY STANDARDS
===============================================================================

Every response must be:

• Valid
• Complete
• Accurate
• Consistent
• Deterministic
• Parseable
• Schema compliant
• Production-ready
• Extensible

===============================================================================
9.30 FINAL VERIFICATION CHECKLIST
===============================================================================

Before returning the response, verify:

• JSON syntax is valid.
• Schema requirements are satisfied.
• Required fields are present.
• Data types are correct.
• Scores are internally consistent.
• Complexity matches the analysis.
• Recommendations are evidence-based.
• No hallucinated information exists.
• Empty collections follow specification.
• Confidence value is valid.
• Response is deterministic.
• Output contains JSON only.

"""